- name: variable to print
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi all, I am learning a Course: DevOps with AWS, Duration: 120HRS, Trainer: Sivakumar Reddy"