- name: variable to print
  hosts: web
  vars:
    COURSE: "DevOps with AWS"
    DURATAION: "120HRS"
    TRAINER: "Sivakumar Reddy"
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi all, I am learning a {{COURSE}}, {{DURATION}}, {{TRAINER}}"