- name: Print the variables
  hosts: web
  var_files:
  - vars.yaml
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi all, i am learning {{COURSE}}, Duration is {{DURATION}} and the Trainer={{TRAINER}}"