- name: Variable to be print in prompt
  hosts: web
  vars_propmt:
  - name: COURSE
    prompt: Please enter course name
  - name: DURATION
    prompt: please enter duration
  - name: TRAINER
    prompt: please enter trainer name
  tasks:
  - name: Print the course information
    ansible.builtin.debug:
      msg: "Hi all, i am learning {{COURSE}}, Duration is {{DURATION}} and the Trainer={{TRAINER}}"          