- name: Variable to be print in prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter course name
    private: false #not confindential
  - name: DURATION
    prompt: please enter duration
    private: false
  - name: TRAINER
    prompt: please enter trainer name
    private: false
  tasks:
  - name: Print the course information
    ansible.builtin.debug:
      msg: "Hi all, i am learning {{COURSE}}, Duration is {{DURATION}} and the Trainer={{TRAINER}}"          