- name: print the varaible from inventory files
  hosts: web
  tasks:
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi all, i am learning {{COURSE}}, Duration is {{DURATION}} and the Trainer={{TRAINER}}"