- name: create user
  hosts: web
  bacome: yes
  tasks:
  - name: check user exists or not
    ansible.builtin.command: id expense
    register: USER #in USER variable that gets output from above command
  - name: print user information
    ansible.builtin.debug:
      msg: " User info {{ USER }} "
