- name: Demo on functions
  hosts: local
  connection: local
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default ('ansible') }}"

  - name: convert to uppercase
    vars:
      str: Hi Ramesh
    ansible.builtin.debug:
      msg: "{{ str | upper }}"

  - name: convert to lowercase
    vars:
      str: Hi Ramesh
    ansible.builtin.debug:
      msg: "{{ str | lower }}"     