- name: Demo on functions
  hosts: local
  connection: local
  tasks:
  - name: print the default value
    ansible.builtin.debug:
      msg: "Hello {{ course | default ('ansible') }}"

  - name: convert to uppercase
    vars:
      str: Hi Ramesh
    ansible.builtin.debug:
      msg: "{{ str | upper }}"

  - name: convert to lowercase
    vars:
      str: Hi Ramesh
    ansible.builtin.debug:
      msg: "{{ str | lower }}"    

  - name: Unique numbers
    vars:
      num: [ 1, 3, 3, 5, 3, 7, 5, 8, 5, 6 ]
    ansible.builtin.debug:
      msg: "{{ num | unique }}" 

  - name: Maximum of number
    vars:
      num: [ 23, 25, 45 ]
    ansible.builtin.debug:
      msg: "{{ num | max }}" 

  - name: Minimum of number
    vars:
      num: [ 23, 25, 45 ]
    ansible.builtin.debug:
      msg: "{{ num | min }}" 
  

  - name: convert map to list
    vars:
      course:
        name: "DevOps with AWS"
        duration: 120
        trainer: "Sivakumar"
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"       

  - name: convert map to list
    vars:
      course:
      -  { "key": "name", "value": "DevOps with AWS" }
      -  { "key": "duration", "value": 120 }
      -  { "key": "trainer", "value": "Sivakumar" }
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}" 

  - name: check ip address
    vars:
      myip: 358.34.23.1
    ansible.builtin.debug:
      msg: "{{ myip | ansible.utils.ipv4 }}" 