- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    instance:
    - mysql
    - backend
    - frontend
    zone: khaleja.fun
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name: 
      - boto3
      - botocore
      executable: pip3.9

  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: subnet-05ab30fcf1a1ff260
      instance_type: t3.micro
      security_group: sg-0efcd8315a973a0e8
      image_id: ami-0220d79f3f480ecf5
    loop: "{{ instance }}"
    register: ec2_instance

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_instance }}"

  - name: create r53 records for private ips
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.khaleja.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instance.results }}"

  - name: create  r53 records for public ip
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #khaleja.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instance.results }}"
    when: item.item == "frontend" 