[web]
172.31.23.215


[web:vars]
COURSE="Devops with AWS from inventory"
DURATION="127HRS"
TRAINER="Sivakumar Reddy"

[backend]
172.31.27.250


[mysql]
172.31.29.20


 
[servers:children]
backend
mysql

[web:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local]
localhost


