# - name: ping the server
#   hosts: web
#   tasks:
#   - name: ping information
#     ansible.builtin.ping:


- name: variable to be print
  hosts: web
  vars:
    COURSE: DevOps
  tasks:
    - name: print the course information
      ansible.builtin.debug:
        msg: "I am learning {{COURSE}}"
    - name: print the course ingo again 
      vars:
        COURSE: ansible
      ansible.builtin.debug:
        msg: "I am learning {{COURSE}}"